version: '3.8'
services:
  database:
    container_name: "mariadb_host"
    image: mariadb:10.8.3
    ports:
      - '3306:3306'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'maria'
      MARIADB_DATABASE: 'news_release'
      MARIADB_USER: 'news'
      MARIADB_PASSWORD: 'foobarhogepiyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql

  redis:
    container_name: 'redis_session'
    image: redis:7.0.2
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data